import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/themeprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-dark">
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
       
        {children}
        </ThemeProvider>
        <script src="node_modules/@material-tailwind/html/scripts/collapse.js"></script>
         <script src="https://unpkg.com/@material-tailwind/html@latest/scripts/collapse.js"></script>
        </body>
    </html>
  );
}
